### ISSUE TITLE
HEIC Images thumbnailing now works in Icaros 3.3.3 Beta 1 but thumbnails are extremely zoomed in squares compared to actual thumbnail

### ISSUE THREAD

**Issue by 7eventech77** [Xanashi/Icaros#105]
Updated from Icaros 3.3.2 where HEIC thumbnailing did not work for me at all to 3.3.3 Beta 1. HEIC thumbnailing now works. However, the thumbnails are all extremely zoomed in 4:3 images even on 16:9 images. Not sure why this is the case but is probably a bug.

First time posting on this github page so let me know any information or debug information you need to help fix the problem and how to retrieve it and I will do it.

Thank you!

**Comment by snakehill** [comment]
Same here. HEIC thumbnails on Windows have never been as fast as they are with Icaros 3.3.3b1, but they are all zoomed in and unusable.

Something else that the beta is causing is that now when opening the HEIC images (e.g. in Windows Photos and Photo Viewer), it shows a zoomed-in version reminiscent of the faulty thumbnail for like half a second, before zooming out and showing the image in full. Without Icaros or with 3.3.2, Windows shows the full image right away for me.

**Comment by 7eventech77** [comment]
Good to hear that I'm not the only one experiencing this. I was happy that HEIC thumbnails were finally working but was confused about the zooming in. I'm not experiencing the 2nd issue you have but I'm using ImageGlass as my photo viewer so that is most likely why

**Comment by snakehill** [comment]
> I'm not experiencing the 2nd issue you have but I'm using ImageGlass as my photo viewer so that is most likely why

If you **right-click > Open with > Photos** (or Windows Photo Viewer if you happen to have it) you should experience the same.

This particular sub-issue could be more so a Windows thing than an Icaros thing, that perhaps Windows loads the thumbnail as a first, quicker preview for HEIC files with the full image loading slower afterwards, but given that the thumbnail is broken, that breaks such a first look too.

**Comment by 7eventech77** [comment]
Quite possibly. I tested what you said and the issue happens for me too.

**Comment by Xanashi** [comment]
I see the issue, and know what's causing it. I will work on a fix right away.
I only have a single file where this issue is present, so if any of you could provide me with additional HEIC files
where this problem shows, that would be a big help.

The Windows Photos app is a bit of a black box, when it comes to how it interacts with filetypes and codecs in Windows,
but I think it's safe to say that snakehills assumption, that it uses the thumbnail as a quick preview while loading the full
image, is correct.

**Comment by snakehill** [comment]
> I only have a single file where this issue is present, so if any of you could provide me with additional HEIC files
> where this problem shows, that would be a big help.

Great to hear the reason is known! For some extra files, it seems to happen with the first 3 images of https://github.com/tigranbs/test-heic-images/tree/master

**Comment by Xanashi** [comment]
Thank you!

**Comment by Xanashi** [comment]
This should be fixed in 3.3.3 Beta 2:
[https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b2](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b2)

**Comment by 7eventech77** [comment]
> This should be fixed in 3.3.3 Beta 2: https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b2

Thank you! Completely forgot to send in images for you, sorry about that.

However, after updating there is a different issue. The bug where is was zoomed in a bunch is confirmed fixed but now images are smooshed down and portraits are shown as landscapes. Almost all .heic images are like this except a few using a different camera I had. No idea what the issue is. See the before and after photos. (Before is using https://github.com/saschanaz/jxl-winthumb/) Icaros is much much faster at thumbnailing once it finishes hanging up for 5 seconds trying to thumbnail .heics in images than this project though.[
![Before Update](https://github.com/user-attachments/assets/89e58403-7fed-41b0-86c9-3c054da447d2)
![After Update](https://github.com/user-attachments/assets/9a45cf59-e792-4b08-893b-bcf1569f62f3)
](url)

**Comment by Xanashi** [comment]
Yeah, that doesn't seem right. Could you send me some of these HEICs? Then I can check it out ASAP.
I didn't quite understand the last sentence. Is there a hang with Icaros?

**Comment by 7eventech77** [comment]
Yes, there is a hang before they all load at once which is really strange. I'll send you the files above and a short clip of what it is doing. Also, just noticed that no properties information is showing either for the .heic images. Not even basic stuff which is weird. Not sure how much it had before but doesn't seem right

**Comment by Xanashi** [comment]
The hang could be caused by the [MS HEIF Image extensions](https://apps.microsoft.com/detail/9pmmsr1cgpwg?hl=en-us&gl=SE).
I've seen this issue before, and after uninstalling that package, the hanging in Explorer stopped.

Icaros doesn't handle HEIC properties at this time, so if you've had properties showing for HEIC files, it must've been from another
shell extension.

**Comment by 7eventech77** [comment]
Here you go
https://github.com/7eventech77/test-heic-images


https://github.com/user-attachments/assets/e7a6030b-ec97-4826-87ac-2b28beb925a1

I do have the MS HEIF Image extensions installed. I'll have remove it and see if it improves

And okay on the properties, wasn't sure if it was supported or not. At least that is isn't a bug for now.

**Comment by Xanashi** [comment]
Thank you. I'll check out the test files, and will get back to you.
Let me know if uninstalling the MS extensions work.

**Comment by 7eventech77** [comment]
> Thank you. I'll check out the test files, and will get back to you. Let me know if uninstalling the MS extensions work.

Removed the MS extensions and rebooted. Still does the same hang. And thank you! Would love to get this working properly.

**Comment by Xanashi** [comment]
Hmm. That's annoying, I'm not quite sure what else could be causing them.
I personally don't have any hangs on my end, so it's hard to troubleshoot.

Edit: If you have any other MS extensions installed, you could also try and remove them.

**Comment by 7eventech77** [comment]
> Hmm. That's annoying, I'm not quite sure what else could be causing them. I personally don't have any hangs on my end, so it's hard to troubleshoot.
> 
> Edit: If you have any other MS extensions installed, you could also try and remove them.

Okay I will try that. I just added another feature request about .avif, it does the same "hang" as .heic as well which is odd

**Comment by 7eventech77** [comment]
normal Jpegs are doing the same hang so must be something on my end, ignore that for now unless you find something. I'll let you know if I figure out anything. Continue on with the fix for the image resizing

**Comment by 7eventech77** [comment]
Removed MPEG2 Video Extensions, WebP Extension, External Webp codec extension and the hang went away. If anyone else has the issue then let them know to remove them for troubleshooting 👍

**Comment by snakehill** [comment]
I personally don't seem to have the smoosh issue, only the rotation one. HEIC is known to rotate non-destructively (opposed to JPG/PNG) in that it changes the metadata for the rotation instead of the actual pixels/image, so Icaros would probably need to check said metadata.

On the whole, it's looking incredibly promising. Compared to any other HEIC thumbnailer, this beats it hands down in terms of speed.

**Comment by Xanashi** [comment]
> Removed MPEG2 Video Extensions, WebP Extension, External Webp codec extension and the hang went away. If anyone else has the issue then let them know to remove them for troubleshooting 👍

That's awesome. Glad you got it fixed. 
I have a sneaking suspicion it may be the WebP Extension that's causing the issue. 

Btw I noticed that I have full properties for all my HEIC files, so I looked into it, and the native MS image property handler does actually handle HEIC files, so you probably just need to fix it in the registry. 

Try merging the following .reg and refresh Explorer.
[heic-properties.reg.txt](https://github.com/user-attachments/files/16263823/heic-properties.reg.txt)
(remove .txt file extension first)

**Comment by Xanashi** [comment]
@7eventech77 Could you try the following build:
[https://www.mediafire.com/file/ozx9wjlbvof2v8j/Icaros_v3.3.3_b2_test.zip/file](https://www.mediafire.com/file/ozx9wjlbvof2v8j/Icaros_v3.3.3_b2_test.zip/file)
It should fix the aspect ratio issue.

**Comment by Xanashi** [comment]
> I personally don't seem to have the smoosh issue, only the rotation one. HEIC is known to rotate non-destructively (opposed to JPG/PNG) in that it changes the metadata for the rotation instead of the actual pixels/image, so Icaros would probably need to check said metadata.
> 
> On the whole, it's looking incredibly promising. Compared to any other HEIC thumbnailer, this beats it hands down in terms of speed.

I'm very glad to hear that! 

I'll look into the rotation issue, it shouldn't be too hard to fix. Do you have a few sample files with rotation metadata?

**Comment by snakehill** [comment]
> Do you have a few sample files with rotation metadata?

https://borealisdata.ca/dataset.xhtml?persistentId=doi:10.5683/SP3/RQAUCI

Now you've got both sample collections I tend to use as quick HEIC tests, that one specifically for the rotation. 😄

As for the metadata, it's Rotation: 0/90/180/270 (there also is an Orientation tag but those tend to bit more random, like "Normal" or "Rotate 90/180 CW/CCW").

**Comment by 7eventech77** [comment]
> @7eventech77 Could you try the following build: https://www.mediafire.com/file/ozx9wjlbvof2v8j/Icaros_v3.3.3_b2_test.zip/file It should fix the aspect ratio issue.

Tried the build, fixes the aspect ratio issue. Of course rotation is still not working. Tried the .reg file and that fixed the properties to where they display now for .heic files. 👍 
![after beta build](https://github.com/user-attachments/assets/679794bc-a112-42d2-b83a-3a420a5f11a9)

**Comment by Xanashi** [comment]
@7eventech77 Perfect thank you for testing! and glad the .reg worked for you.

@snakehill, @7eventech77 Could you try this build and see if it fixes orientation for all your HEIC files:
https://www.mediafire.com/file/xb6zddwdy6ynr73/Icaros_v3.3.2_b2_test2.zip/file

**Comment by snakehill** [comment]
> Could you try this build and see if it fixes orientation for all your HEIC files:
> https://www.mediafire.com/file/xb6zddwdy6ynr73/Icaros_v3.3.2_b2_test2.zip/file

Yes! All fine for me, awesome!

**Comment by Xanashi** [comment]
Awesome, thank you snakehill.
I did notice a small bug with the code which I've just fixed, so if certain files doesn't rotate correctly in the above
test build, that's probably why. I'll upload another test build soon.

**Comment by 7eventech77** [comment]
> @7eventech77 Perfect thank you for testing! and glad the .reg worked for you.
> 
> @snakehill, @7eventech77 Could you try this build and see if it fixes orientation for all your HEIC files: https://www.mediafire.com/file/xb6zddwdy6ynr73/Icaros_v3.3.2_b2_test2.zip/file

Yep it is fixed! Thank you!

![After new build](https://github.com/user-attachments/assets/6a4ae48a-e8e0-4dd7-aadc-78403cead3e3)

**Comment by Xanashi** [comment]
Thank you both so much for testing and providing sample files and screenshots.
Here is the last test build, where the bug I mentioned yesterday has been fixed (although, I don't believe neither of you were affected by it):
https://www.mediafire.com/file/doaxfdutfc2l73u/Icaros_v3.3.3_b2_test3.zip/file

**Comment by 7eventech77** [comment]
> Thank you both so much for testing and providing sample files and screenshots. Here is the last test build, where the bug I mentioned yesterday has been fixed (although, I don't believe neither of you were affected by it): https://www.mediafire.com/file/doaxfdutfc2l73u/Icaros_v3.3.3_b2_test3.zip/file

As of this build, all HEIC issues I have are fixed. I'll let you know if I have anything else. Thank you so much for listening!

**Comment by Xanashi** [comment]
You're very welcome. Thank you so much for testing, and providing samples and screenshots!
I'll close this issue after the next release of Icaros.

**Comment by 7eventech77** [comment]
> You're very welcome. Thank you so much for testing, and providing samples and screenshots! I'll close this issue after the next release of Icaros.

You are most welcome! Thank you!

**Comment by Xanashi** [comment]
All of these fixes have finally been included in [3.3.3 Beta 3](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b3), so we can close this for now. 

Thank you both for all your help!
